---
# tasks file for sudo_config
- name: debug
  debug:
    msg: "group : {{ sudo_file_item }}"

- name: Copy file
  copy:
    src: "{{ sudoers_files_path }}/{{ sudo_file_item }}"
    dest: "{{ staging_dir }}"
    backup: no
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -csf %s
  register: sudoers_d

- name: Test and activate sudoers files
  block:
    - name: Backup current directory
      copy:
        src: "{{ sudoers_path }}"
        dest: "{{ sudoers_bck_path }}"
        owner: root
        group: root
        mode: "preserve"
        remote_src: true

    - name: Move new files
      copy:
        src: "{{ staging_dir }}/{{ sudo_file_item }}"
        dest: "{{ sudoers_path }}"
        owner: root
        group: root
        mode: "0440"
        remote_src: true
    
    - name: Validate config
      command: /usr/sbin/visudo -c    

  rescue:
    - name: Remove corrupt config
      file:
        path: {{ sudoers_path }}
        state: absent

    - name: Restore backup
      copy:
        src: "{{ sudoers_bck_path }}"
        dest: "{{ sudoers_path }}"
        remote_src: true

    - name: Get files list
      find: 
        paths: "{{ sudoers_path }}"
      register: file_list

    - name: Set file permissions
      file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: "0440"
      with_items: "{{ file_list.files }}"
        
    - name: Remove corrupt file
      file:
        path: "{{ staging_dir }}/{{ sudo_file_item }}"
        state: absent

  always:
    - name: Remove useless directory
      file:
        path: "{{ sudoers_bck_path }}"
        state: absent

  when: sudoers_d.changed

